### ISSUE TITLE
Confetti CSS Button

### ISSUE THREAD

**Issue by ZoeLeBlanc** [nss-day-cohort-16/cohort-16-website#8]
### Feature Description
_A description of the desired functionality_
- confetti css button function for party mode
### Recommended Actions
_List out recommended actions include property, file, and method names_

### Related Issues/PRs
_If this is related to any other issues or PRs then add them here_

**Comment by nathantbaker** [comment]
http://codepen.io/gamanox/pen/FkEbH

**Comment by ben-d-marks** [comment]
Refactor JS to add custom div with random attributes, instead of hard-coded divs and css classes
